package phrille.minecraftboom.init;

import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraftforge.registries.ObjectHolder;
import phrille.minecraftboom.MinecraftBoom;
import phrille.minecraftboom.util.Utils;

@ObjectHolder(MinecraftBoom.MOD_ID)
public class ModBlocks
{
    //Bricks
    public static final Block COBBLESTONE_BRICKS = Utils._null();
    public static final Block MOSSY_COBBLESTONE_BRICKS = Utils._null();
    public static final Block MAGMA_BRICKS = Utils._null();
    public static final Block OBSIDIAN_BRICKS = Utils._null();
    public static final Block TERRACOTTA_BRICKS = Utils._null();
    public static final Block WHITE_TERRACOTTA_BRICKS = Utils._null();
    public static final Block ORANGE_TERRACOTTA_BRICKS = Utils._null();
    public static final Block MAGENTA_TERRACOTTA_BRICKS = Utils._null();
    public static final Block LIGHT_BLUE_TERRACOTTA_BRICKS = Utils._null();
    public static final Block YELLOW_TERRACOTTA_BRICKS = Utils._null();
    public static final Block LIME_TERRACOTTA_BRICKS = Utils._null();
    public static final Block PINK_TERRACOTTA_BRICKS = Utils._null();
    public static final Block GRAY_TERRACOTTA_BRICKS = Utils._null();
    public static final Block LIGHT_GRAY_TERRACOTTA_BRICKS = Utils._null();
    public static final Block CYAN_TERRACOTTA_BRICKS = Utils._null();
    public static final Block PURPLE_TERRACOTTA_BRICKS = Utils._null();
    public static final Block BLUE_TERRACOTTA_BRICKS = Utils._null();
    public static final Block BROWN_TERRACOTTA_BRICKS = Utils._null();
    public static final Block GREEN_TERRACOTTA_BRICKS = Utils._null();
    public static final Block RED_TERRACOTTA_BRICKS = Utils._null();
    public static final Block BLACK_TERRACOTTA_BRICKS = Utils._null();

    //Gravel
    public static final Block FINE_GRAVEL = Utils._null();
    public static final Block GRAVEL_STONE = Utils._null();
    public static final Block FINE_GRAVEL_STONE = Utils._null();
    public static final Block GRAVEL_BRICKS = Utils._null();

    //Polished
    public static final Block POLISHED_PRISMARINE = Utils._null();
    public static final Block POLISHED_DARK_PRISMARINE = Utils._null();
    public static final Block POLISHED_END_STONE = Utils._null();
    public static final Block POLISHED_NETHERRACK = Utils._null();

    //Pillars
    public static final Block GRANITE_PILLAR = Utils._null();
    public static final Block DIORITE_PILLAR = Utils._null();
    public static final Block ANDESITE_PILLAR = Utils._null();
    public static final Block PRISMARINE_PILLAR = Utils._null();
    public static final Block DARK_PRISMARINE_PILLAR = Utils._null();
    public static final Block END_STONE_PILLAR = Utils._null();
    public static final Block NETHERRACK_PILLAR = Utils._null();

    //Storage
    public static final Block CHARCOAL_BLOCK = Utils._null();
    public static final Block SUGAR_BLOCK = Utils._null();
    public static final Block SUGAR_CANE_BLOCK = Utils._null();
    public static final Block GUNPOWDER_BLOCK = Utils._null();
    public static final Block BLAZE_POWDER_BLOCK = Utils._null();
    public static final Block MAGMA_CREAM_BLOCK = Utils._null();
    public static final Block PRISMARINE_CRYSTAL_BLOCK = Utils._null();
    public static final Block WITHER_BONE_BLOCK = Utils._null();
    public static final Block WHITE_DYE_BLOCK = Utils._null();
    public static final Block ORANGE_DYE_BLOCK = Utils._null();
    public static final Block MAGENTA_DYE_BLOCK = Utils._null();
    public static final Block LIGHT_BLUE_DYE_BLOCK = Utils._null();
    public static final Block YELLOW_DYE_BLOCK = Utils._null();
    public static final Block LIME_DYE_BLOCK = Utils._null();
    public static final Block PINK_DYE_BLOCK = Utils._null();
    public static final Block GRAY_DYE_BLOCK = Utils._null();
    public static final Block LIGHT_GRAY_DYE_BLOCK = Utils._null();
    public static final Block CYAN_DYE_BLOCK = Utils._null();
    public static final Block PURPLE_DYE_BLOCK = Utils._null();
    public static final Block BROWN_DYE_BLOCK = Utils._null();
    public static final Block GREEN_DYE_BLOCK = Utils._null();
    public static final Block RED_DYE_BLOCK = Utils._null();
    public static final Block BLACK_DYE_BLOCK = Utils._null();

    //Glass
    public static final Block SOUL_GLASS = Utils._null();
    public static final Block WHITE_STAINED_SOUL_GLASS = Utils._null();
    public static final Block ORANGE_STAINED_SOUL_GLASS = Utils._null();
    public static final Block MAGENTA_STAINED_SOUL_GLASS = Utils._null();
    public static final Block LIGHT_BLUE_STAINED_SOUL_GLASS = Utils._null();
    public static final Block YELLOW_STAINED_SOUL_GLASS = Utils._null();
    public static final Block LIME_STAINED_SOUL_GLASS = Utils._null();
    public static final Block PINK_STAINED_SOUL_GLASS = Utils._null();
    public static final Block GRAY_STAINED_SOUL_GLASS = Utils._null();
    public static final Block LIGHT_GRAY_STAINED_SOUL_GLASS = Utils._null();
    public static final Block CYAN_STAINED_SOUL_GLASS = Utils._null();
    public static final Block PURPLE_STAINED_SOUL_GLASS = Utils._null();
    public static final Block BLUE_STAINED_SOUL_GLASS = Utils._null();
    public static final Block BROWN_STAINED_SOUL_GLASS = Utils._null();
    public static final Block GREEN_STAINED_SOUL_GLASS = Utils._null();
    public static final Block RED_STAINED_SOUL_GLASS = Utils._null();
    public static final Block BLACK_STAINED_SOUL_GLASS = Utils._null();
    public static final Block SOUL_GLASS_PANE = Utils._null();
    public static final Block WHITE_STAINED_SOUL_GLASS_PANE = Utils._null();
    public static final Block ORANGE_STAINED_SOUL_GLASS_PANE = Utils._null();
    public static final Block MAGENTA_STAINED_SOUL_GLASS_PANE = Utils._null();
    public static final Block LIGHT_BLUE_STAINED_SOUL_GLASS_PANE = Utils._null();
    public static final Block YELLOW_STAINED_SOUL_GLASS_PANE = Utils._null();
    public static final Block LIME_STAINED_SOUL_GLASS_PANE = Utils._null();
    public static final Block PINK_STAINED_SOUL_GLASS_PANE = Utils._null();
    public static final Block GRAY_STAINED_SOUL_GLASS_PANE = Utils._null();
    public static final Block LIGHT_GRAY_STAINED_SOUL_GLASS_PANE = Utils._null();
    public static final Block CYAN_STAINED_SOUL_GLASS_PANE = Utils._null();
    public static final Block PURPLE_STAINED_SOUL_GLASS_PANE = Utils._null();
    public static final Block BLUE_STAINED_SOUL_GLASS_PANE = Utils._null();
    public static final Block BROWN_STAINED_SOUL_GLASS_PANE = Utils._null();
    public static final Block GREEN_STAINED_SOUL_GLASS_PANE = Utils._null();
    public static final Block RED_STAINED_SOUL_GLASS_PANE = Utils._null();
    public static final Block BLACK_STAINED_SOUL_GLASS_PANE = Utils._null();

    //Misc
    public static final Block GOLD_BARS = Utils._null();
    public static final Block ROSE = Utils._null();
    
    //MinecraftBoom Stairs
    public static final Block COBBLESTONE_BRICK_STAIRS = Utils._null();
    public static final Block MOSSY_COBBLESTONE_BRICK_STAIRS = Utils._null();
    public static final Block MAGMA_BRICK_STAIRS = Utils._null();
    public static final Block OBSIDIAN_BRICK_STAIRS = Utils._null();
    public static final Block TERRACOTTA_BRICK_STAIRS = Utils._null();
    public static final Block WHITE_TERRACOTTA_BRICK_STAIRS = Utils._null();
    public static final Block ORANGE_TERRACOTTA_BRICK_STAIRS = Utils._null();
    public static final Block MAGENTA_TERRACOTTA_BRICK_STAIRS = Utils._null();
    public static final Block LIGHT_BLUE_TERRACOTTA_BRICK_STAIRS = Utils._null();
    public static final Block YELLOW_TERRACOTTA_BRICK_STAIRS = Utils._null();
    public static final Block LIME_TERRACOTTA_BRICK_STAIRS = Utils._null();
    public static final Block PINK_TERRACOTTA_BRICK_STAIRS = Utils._null();
    public static final Block GRAY_TERRACOTTA_BRICK_STAIRS = Utils._null();
    public static final Block LIGHT_GRAY_TERRACOTTA_BRICK_STAIRS = Utils._null();
    public static final Block CYAN_TERRACOTTA_BRICK_STAIRS = Utils._null();
    public static final Block PURPLE_TERRACOTTA_BRICK_STAIRS = Utils._null();
    public static final Block BLUE_TERRACOTTA_BRICK_STAIRS = Utils._null();
    public static final Block BROWN_TERRACOTTA_BRICK_STAIRS = Utils._null();
    public static final Block GREEN_TERRACOTTA_BRICK_STAIRS = Utils._null();
    public static final Block RED_TERRACOTTA_BRICK_STAIRS = Utils._null();
    public static final Block BLACK_TERRACOTTA_BRICK_STAIRS = Utils._null();
    public static final Block GRAVEL_STONE_STAIRS = Utils._null();
    public static final Block FINE_GRAVEL_STONE_STAIRS = Utils._null();
    public static final Block GRAVEL_BRICK_STAIRS = Utils._null();
    public static final Block POLISHED_PRISMARINE_STAIRS = Utils._null();
    public static final Block POLISHED_DARK_PRISMARINE_STAIRS = Utils._null();
    public static final Block POLISHED_END_STONE_STAIRS = Utils._null();
    public static final Block POLISHED_NETHERRACK_STAIRS = Utils._null();
    
    //Vanilla Stairs
    public static final Block STONE_STAIRS = Utils._null();
    public static final Block GRANITE_STAIRS = Utils._null();
    public static final Block POLISHED_GRANITE_STAIRS = Utils._null();
    public static final Block DIORITE_STAIRS = Utils._null();
    public static final Block POLISHED_DIORITE_STAIRS = Utils._null();
    public static final Block ANDESITE_STAIRS = Utils._null();
    public static final Block POLISHED_ANDESITE_STAIRS = Utils._null();
    public static final Block MOSSY_COBBLESTONE_STAIRS = Utils._null();
    public static final Block MOSSY_STONE_BRICK_STAIRS = Utils._null();
    public static final Block CRACKED_STONE_BRICK_STAIRS = Utils._null();
    public static final Block CHISELED_STONE_BRICK_STAIRS = Utils._null();
    public static final Block CUT_SANDSTONE_STAIRS = Utils._null();
    public static final Block CHISELED_SANDSTONE_STAIRS = Utils._null();
    public static final Block SMOOTH_SANDSTONE_STAIRS = Utils._null();
    public static final Block CUT_RED_SANDSTONE_STAIRS = Utils._null();
    public static final Block CHISELED_RED_SANDSTONE_STAIRS = Utils._null();
    public static final Block SMOOTH_RED_SANDSTONE_STAIRS = Utils._null();
    public static final Block OAK_WOOD_STAIRS = Utils._null();
    public static final Block SPRUCE_WOOD_STAIRS = Utils._null();
    public static final Block BIRCH_WOOD_STAIRS = Utils._null();
    public static final Block JUNGLE_WOOD_STAIRS = Utils._null();
    public static final Block ACACIA_WOOD_STAIRS = Utils._null();
    public static final Block DARK_OAK_WOOD_STAIRS = Utils._null();
    public static final Block IRON_BLOCK_STAIRS = Utils._null();
    public static final Block GOLD_BLOCK_STAIRS = Utils._null();
    public static final Block OBSIDIAN_STAIRS = Utils._null();
    public static final Block NETHERRACK_STAIRS = Utils._null();
    public static final Block RED_NETHER_BRICK_STAIRS = Utils._null();
    public static final Block END_STONE_STAIRS = Utils._null();
    public static final Block END_STONE_BRICK_STAIRS = Utils._null();
    public static final Block CHISELED_QUARTZ_BLOCK_STAIRS = Utils._null();
    public static final Block TERRACOTTA_STAIRS = Utils._null();
    public static final Block WHITE_TERRACOTTA_STAIRS = Utils._null();
    public static final Block ORANGE_TERRACOTTA_STAIRS = Utils._null();
    public static final Block MAGENTA_TERRACOTTA_STAIRS = Utils._null();
    public static final Block LIGHT_BLUE_TERRACOTTA_STAIRS = Utils._null();
    public static final Block YELLOW_TERRACOTTA_STAIRS = Utils._null();
    public static final Block LIME_TERRACOTTA_STAIRS = Utils._null();
    public static final Block PINK_TERRACOTTA_STAIRS = Utils._null();
    public static final Block GRAY_TERRACOTTA_STAIRS = Utils._null();
    public static final Block LIGHT_GRAY_TERRACOTTA_STAIRS = Utils._null();
    public static final Block CYAN_TERRACOTTA_STAIRS = Utils._null();
    public static final Block PURPLE_TERRACOTTA_STAIRS = Utils._null();
    public static final Block BLUE_TERRACOTTA_STAIRS = Utils._null();
    public static final Block BROWN_TERRACOTTA_STAIRS = Utils._null();
    public static final Block GREEN_TERRACOTTA_STAIRS = Utils._null();
    public static final Block RED_TERRACOTTA_STAIRS = Utils._null();
    public static final Block BLACK_TERRACOTTA_STAIRS = Utils._null();
    public static final Block WHITE_CONCRETE_STAIRS = Utils._null();
    public static final Block ORANGE_CONCRETE_STAIRS = Utils._null();
    public static final Block MAGENTA_CONCRETE_STAIRS = Utils._null();
    public static final Block LIGHT_BLUE_CONCRETE_STAIRS = Utils._null();
    public static final Block YELLOW_CONCRETE_STAIRS = Utils._null();
    public static final Block LIME_CONCRETE_STAIRS = Utils._null();
    public static final Block PINK_CONCRETE_STAIRS = Utils._null();
    public static final Block GRAY_CONCRETE_STAIRS = Utils._null();
    public static final Block LIGHT_GRAY_CONCRETE_STAIRS = Utils._null();
    public static final Block CYAN_CONCRETE_STAIRS = Utils._null();
    public static final Block PURPLE_CONCRETE_STAIRS = Utils._null();
    public static final Block BLUE_CONCRETE_STAIRS = Utils._null();
    public static final Block BROWN_CONCRETE_STAIRS = Utils._null();
    public static final Block GREEN_CONCRETE_STAIRS = Utils._null();
    public static final Block RED_CONCRETE_STAIRS = Utils._null();
    public static final Block BLACK_CONCRETE_STAIRS = Utils._null();
    public static final Block BLOCK_SMOOTH_STONE_STAIRS = Utils._null();
    
    //MinecraftBoom Slabs
    public static final Block COBBLESTONE_BRICK_SLAB = Utils._null();
    public static final Block MOSSY_COBBLESTONE_BRICK_SLAB = Utils._null();
    public static final Block MAGMA_BRICK_SLAB = Utils._null();
    public static final Block OBSIDIAN_BRICK_SLAB = Utils._null();
    public static final Block TERRACOTTA_BRICK_SLAB = Utils._null();
    public static final Block WHITE_TERRACOTTA_BRICK_SLAB = Utils._null();
    public static final Block ORANGE_TERRACOTTA_BRICK_SLAB = Utils._null();
    public static final Block MAGENTA_TERRACOTTA_BRICK_SLAB = Utils._null();
    public static final Block LIGHT_BLUE_TERRACOTTA_BRICK_SLAB = Utils._null();
    public static final Block YELLOW_TERRACOTTA_BRICK_SLAB = Utils._null();
    public static final Block LIME_TERRACOTTA_BRICK_SLAB = Utils._null();
    public static final Block PINK_TERRACOTTA_BRICK_SLAB = Utils._null();
    public static final Block GRAY_TERRACOTTA_BRICK_SLAB = Utils._null();
    public static final Block LIGHT_GRAY_TERRACOTTA_BRICK_SLAB = Utils._null();
    public static final Block CYAN_TERRACOTTA_BRICK_SLAB = Utils._null();
    public static final Block PURPLE_TERRACOTTA_BRICK_SLAB = Utils._null();
    public static final Block BLUE_TERRACOTTA_BRICK_SLAB = Utils._null();
    public static final Block BROWN_TERRACOTTA_BRICK_SLAB = Utils._null();
    public static final Block GREEN_TERRACOTTA_BRICK_SLAB = Utils._null();
    public static final Block RED_TERRACOTTA_BRICK_SLAB = Utils._null();
    public static final Block BLACK_TERRACOTTA_BRICK_SLAB = Utils._null();
    public static final Block GRAVEL_STONE_SLAB = Utils._null();
    public static final Block FINE_GRAVEL_STONE_SLAB = Utils._null();
    public static final Block GRAVEL_BRICK_SLAB = Utils._null();
    public static final Block POLISHED_PRISMARINE_SLAB = Utils._null();
    public static final Block POLISHED_DARK_PRISMARINE_SLAB = Utils._null();
    public static final Block POLISHED_END_STONE_SLAB = Utils._null();
    public static final Block POLISHED_NETHERRACK_SLAB = Utils._null();
    
    //Vanilla Slabs
    public static final Block STONE_SLAB = Utils._null();
    public static final Block GRANITE_SLAB = Utils._null();
    public static final Block POLISHED_GRANITE_SLAB = Utils._null();
    public static final Block DIORITE_SLAB = Utils._null();
    public static final Block POLISHED_DIORITE_SLAB = Utils._null();
    public static final Block ANDESITE_SLAB = Utils._null();
    public static final Block POLISHED_ANDESITE_SLAB = Utils._null();
    public static final Block MOSSY_COBBLESTONE_SLAB = Utils._null();
    public static final Block MOSSY_STONE_BRICK_SLAB = Utils._null();
    public static final Block CRACKED_STONE_BRICK_SLAB = Utils._null();
    public static final Block CHISELED_STONE_BRICK_SLAB = Utils._null();
    public static final Block CUT_SANDSTONE_SLAB = Utils._null();
    public static final Block CHISELED_SANDSTONE_SLAB = Utils._null();
    public static final Block SMOOTH_SANDSTONE_SLAB = Utils._null();
    public static final Block CUT_RED_SANDSTONE_SLAB = Utils._null();
    public static final Block CHISELED_RED_SANDSTONE_SLAB = Utils._null();
    public static final Block SMOOTH_RED_SANDSTONE_SLAB = Utils._null();
    public static final Block OAK_WOOD_SLAB = Utils._null();
    public static final Block SPRUCE_WOOD_SLAB = Utils._null();
    public static final Block BIRCH_WOOD_SLAB = Utils._null();
    public static final Block JUNGLE_WOOD_SLAB = Utils._null();
    public static final Block ACACIA_WOOD_SLAB = Utils._null();
    public static final Block DARK_OAK_WOOD_SLAB = Utils._null();
    public static final Block IRON_BLOCK_SLAB = Utils._null();
    public static final Block GOLD_BLOCK_SLAB = Utils._null();
    public static final Block OBSIDIAN_SLAB = Utils._null();
    public static final Block NETHERRACK_SLAB = Utils._null();
    public static final Block RED_NETHER_BRICK_SLAB = Utils._null();
    public static final Block END_STONE_SLAB = Utils._null();
    public static final Block END_STONE_BRICK_SLAB = Utils._null();
    public static final Block CHISELED_QUARTZ_BLOCK_SLAB = Utils._null();
    public static final Block TERRACOTTA_SLAB = Utils._null();
    public static final Block WHITE_TERRACOTTA_SLAB = Utils._null();
    public static final Block ORANGE_TERRACOTTA_SLAB = Utils._null();
    public static final Block MAGENTA_TERRACOTTA_SLAB = Utils._null();
    public static final Block LIGHT_BLUE_TERRACOTTA_SLAB = Utils._null();
    public static final Block YELLOW_TERRACOTTA_SLAB = Utils._null();
    public static final Block LIME_TERRACOTTA_SLAB = Utils._null();
    public static final Block PINK_TERRACOTTA_SLAB = Utils._null();
    public static final Block GRAY_TERRACOTTA_SLAB = Utils._null();
    public static final Block LIGHT_GRAY_TERRACOTTA_SLAB = Utils._null();
    public static final Block CYAN_TERRACOTTA_SLAB = Utils._null();
    public static final Block PURPLE_TERRACOTTA_SLAB = Utils._null();
    public static final Block BLUE_TERRACOTTA_SLAB = Utils._null();
    public static final Block BROWN_TERRACOTTA_SLAB = Utils._null();
    public static final Block GREEN_TERRACOTTA_SLAB = Utils._null();
    public static final Block RED_TERRACOTTA_SLAB = Utils._null();
    public static final Block BLACK_TERRACOTTA_SLAB = Utils._null();
    public static final Block WHITE_CONCRETE_SLAB = Utils._null();
    public static final Block ORANGE_CONCRETE_SLAB = Utils._null();
    public static final Block MAGENTA_CONCRETE_SLAB = Utils._null();
    public static final Block LIGHT_BLUE_CONCRETE_SLAB = Utils._null();
    public static final Block YELLOW_CONCRETE_SLAB = Utils._null();
    public static final Block LIME_CONCRETE_SLAB = Utils._null();
    public static final Block PINK_CONCRETE_SLAB = Utils._null();
    public static final Block GRAY_CONCRETE_SLAB = Utils._null();
    public static final Block LIGHT_GRAY_CONCRETE_SLAB = Utils._null();
    public static final Block CYAN_CONCRETE_SLAB = Utils._null();
    public static final Block PURPLE_CONCRETE_SLAB = Utils._null();
    public static final Block BLUE_CONCRETE_SLAB = Utils._null();
    public static final Block BROWN_CONCRETE_SLAB = Utils._null();
    public static final Block GREEN_CONCRETE_SLAB = Utils._null();
    public static final Block RED_CONCRETE_SLAB = Utils._null();
    public static final Block BLACK_CONCRETE_SLAB = Utils._null();
}
